### PR TITLE
Fix country Kenya name typo

### PR DESCRIPTION
**Pull request by kevinsamoei**
The correct spelling for the country is Kenya. This fixes the typo.

### CODE REVIEW

**Comment by gerryster** [comment]
Thanks! Do you want to add your name to the contributors list in package.json?

I am trying to track down the TravisCI build failure on this one. I will pull your branch down locally and see if I get the same results.

**Comment by kevinsamoei** [comment]
> Thanks! Do you want to add your name to the contributors list in package.json?
> 
> I am trying to track down the TravisCI build failure on this one. I will pull your branch down locally and see if I get the same results.

I was able to fix the tests by running `npx mocha test/all.mocha.js --writetests` and it changed several files. Let me know if that is okay.

**Comment by gerryster** [comment]
@kevinsamoei : the Brazil test failures appear to be an issue on master (https://travis-ci.org/commenthol/date-holidays/jobs/551601077) which appeared in the last 15 days. On the surface, it appears as though a change to the operating system's timezone database is causing the issue. I will take a deeper look and get this fixed on master.

With that being said, you should not have to regenerate any test fixtures based on your original change. Let me get back to you regarding the test fixes.

**Comment by commenthol** [comment]
Hi all, yes it may be the case that timezone changes in moment-timezone change the testset. 
I don't have understood in detail why testcases in the past are affected as well.

**Comment by commenthol** [comment]
Ok just checked the files, everything correct - seams that Brazil has changed their official timezone.

**Comment by commenthol** [comment]
Thanks a lot for fixing. Sorry for the typo...

**Pull request merged**
