### PR TITLE
a test case and a fix for commenthol/date-holidays#16

### PR DESCRIPTION
**Pull request by arty-name**
Fix commenthol/date-holidays#16 by filtering out duplicates by name

### CODE REVIEW

**Comment by commenthol** [comment]
Hi @arty-name, Thanks for contributing. Unfortunately this proposal breaks a lot of other countries holidays. Filtering by name might work for DE but others fail where names are not unique across different days. It would be necessary for filter for name and date as well in this case.

**Comment by arty-name** [comment]
Oh, right, I didn’t run the full test suite, my bad. Now I have added the comparison by date as well, but a lot of tests still fails because they expect duplicated data in the output. Should I fix them as well? I guess "public" holidays should take precedence over "observance", right?

**Comment by commenthol** [comment]
Public holidays should have the following order as from README.md "Types of holidays"

| type        | meaning                                    |
| ----------- | ------------------------------------------ |
| public      | public holiday                             |
| bank        | bank holiday, banks and offices are closed |
| school      | school holiday, schools are closed         |
| optional    | majority of people take a day off          |
| observance  | optional festivity, no paid day off        |

To rewrite test cases you may use
`mocha test/all.mocha.js --writetests`

**Comment by commenthol** [comment]
Please check PR #19. Hope that fits your needs.

**Comment by arty-name** [comment]
Thanks, that really helped! I didn’t do that myself because of the vacation.

**Pull request closed without merging**
