### PR TITLE
Fixes #142 GA Confederate Memorial Day 2020

### LINKED ISSUE #142: State Holiday incorrect (Subdivision: US-GA / Year: 2020)
Per https://georgia.gov/popular-topic/state-holidays Friday, April 10 is a State Holiday (i.e. Confederate Memorial Day) in 2020, however we are currently getting 2020-04-27

https://github.com/commenthol/date-holidays/blob/master/data/countries/US.yaml#L293

### PR DESCRIPTION
**Pull request by svict4**

### CODE REVIEW

**Comment by gerryster** [comment]
@svict4 : thanks for the PR. Can you point me to a reference for the 2020 date change on this? Most of what I am seeing suggests that this is no longer an official holiday:

* https://www.ajc.com/blog/politics/why-monday-longer-confederate-memorial-day-georgia/55scplUOZWOIbAzmMKZnXM/
* https://www.al.com/news/2015/10/georgia_does_away_with_confede.html
* https://georgiainfo.galileo.usg.edu/topics/history/article/the-leo-frank-case/confederate-memorial-day-in-georgia
> Although there is no longer a statutory holiday known as Confederate Memorial Day in Georgia, the practice of governors since 1984 has been to proclaim April 26 as Confederate Memorial Day by executive proclamation. While one governor’s proclamations are not binding on the governor that follows, the tradition of celebrating Confederate Memorial Day on April 26 seems secure.

With that said, I am an American who has always lived in the north so I could be missing something here.

**Comment by svict4** [comment]
@gerryster not an American. Was going off http://team.georgia.gov/wp-content/uploads/2019/07/2020-State-Holidays-07.15.19.pdf which still explicitly states April 26th
Probably a better question for @jbroudou on the ticket.
Happy to abandon the PR if you wish 🙂

**Comment by jbroudou** [comment]
@svict4   http://team.georgia.gov/wp-content/uploads/2019/07/2020-State-Holidays-07.15.19.pdf states that the State Holiday will be observed on Friday April 10th in 2020.

> The change doesn't mean the state will not observe the days, however, Deal spokesman Brian Robinson told The Atlanta Journal-Constitution.

> "There will be a state holiday on that day," he said. "Those so inclined can observe Confederate Memorial Day and remember those who died in that conflict."

The day is still a holiday. It has just had its name changed.

**Comment by gerryster** [comment]
@svict4, please don't abandon this PR. Thanks for the link to the link to the memo from the governor. This is an excellent source. Here are my suggestions:

* Add a @source for http://team.georgia.gov/wp-content/uploads/2019/07/2020-State-Holidays-07.15.19.pdf to the YAML file above the 2020 date.
* Chang the holiday name to "State Holiday" per the memo and the current naming.
* Add "note" attribute explaining to @jbroudou's point that this is observed by some as Confedarate Memorial Day.
* If you want to go above and beyond, you could create an actual Confedarate Memorial Day holiday which ends in 2015 per https://www.ajc.com/blog/politics/why-monday-longer-confederate-memorial-day-georgia/55scplUOZWOIbAzmMKZnXM/ .

**Comment by svict4** [comment]
Cool, haven't forgotten about the issue, will get to it this weekend

- [ ] add source, add note
- [ ] "Confedarate Memorial Day" to 2015
- [ ] "State Holiday" from 2016
- [ ] Test/check dates for 2015-2020 data

**Comment by gerryster** [comment]
Sound like a plan @svict4 . Also, here is an example of adding one holiday ending and another begining: https://github.com/commenthol/date-holidays/blob/1e885a0d7950d1c0d898685e07d14e5dce9acfbd/data/countries/US.yaml#L155-L161 .

**Comment by commenthol** [comment]
@svict4 any update on this one?

**Comment by gerryster** [comment]
This has been superseded by #192 .

**Pull request closed without merging**
