### PR TITLE
Israeli holidays: fix Mimouna date and add alternative names

### PR DESCRIPTION
**Pull request by oprogramador**
per https://github.com/commenthol/date-holidays/pull/296/files#r782689108

I'm not Israeli and I have never been in Israel but Jewish holidays are my point of interest.

### CODE REVIEW

**Comment by oprogramador** [comment]
I'm not sure whether I have to change anything else like e.g. some test fixtures.

**Comment by commenthol** [comment]
Hi @oprogramador ,
Please run 
```
npx mocha test/all.mocha.js --writetests --countries IL
```
to regenerate the fixtures. 
Details are in CONTRIBUTING.md
Thanks.

**Comment by oprogramador** [comment]
> npx mocha test/all.mocha.js --writetests --countries IL

Thanks

**Comment by oprogramador** [comment]
> Hi @oprogramador , Please run
> 
> ```
> npx mocha test/all.mocha.js --writetests --countries IL
> ```
> 
> to regenerate the fixtures. Details are in CONTRIBUTING.md Thanks.

Thanks but I'm getting this:
```
⟩ npx mocha test/all.mocha.js --writetests --countries IL

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/me/date-holidays/src/data.js' imported from /home/me/date-holidays/src/Holidays.js
    at finalizeResolution (internal/modules/esm/resolve.js:285:11)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36)
```

**Comment by commenthol** [comment]
You'll need to apply the previous steps as described in CONTRIBUTING as well.

**Comment by oprogramador** [comment]
I have the same problem already for `npm run build`:

```
⟩ npm run build

> date-holidays@3.14.1 build /home/me/date-holidays
> rollup -c


./src/index.js → lib...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
date-holidays-parser (imported by src/Holidays.js)
[!] Error: Could not resolve './data.js' from src/Holidays.js
Error: Could not resolve './data.js' from src/Holidays.js
```

**Comment by oprogramador** [comment]
There's no `data.js` file in https://github.com/commenthol/date-holidays/tree/master/src

**Comment by oprogramador** [comment]
`npm run build` worked after `npm run yaml`.

However, it doesn't seem to have changed any files.

**Comment by oprogramador** [comment]
I decided to join Mimouna with 7th of Pesach because AFAIK they are always on the same day and YAML doesn't allow any key duplications.

**Comment by commenthol** [comment]
Thanks

**Pull request merged**
