### PR TITLE
fix(AU): Update all of Australia 🦘🐨🔥

### PR DESCRIPTION
**Pull request by svict4**
TODO
- [x] Remove Christmas Eve as default holiday (only some states have a partial holiday on Christmas Eve)
- [x] Add partial Christmas Eve for specific states (NT, SA, QLD)
- [x] Fix New Years Eve
- [x] There is no substitute for ANZAC day in most states
- [x] Test it!

Check against legislation for year 2020 (and future years)
- [x] ACT https://www.legislation.act.gov.au/a/1958-19
- [x] NSW https://www.legislation.nsw.gov.au/~/pdf/view/act/2010/115/whole
- [x] NT https://legislation.nt.gov.au/en/Legislation/PUBLIC-HOLIDAYS-ACT-1981
- [x] QLD https://www.legislation.qld.gov.au/view/html/inforce/current/act-1983-018
- [x] SA https://www.legislation.sa.gov.au/LZ/C/A/HOLIDAYS%20ACT%201910.aspx
- [x] TAS https://www.legislation.tas.gov.au/view/html/inforce/current/act-2000-096
- [x] VIC [http://www.legislation.vic.gov.au/](http://www.legislation.vic.gov.au/domino/Web_Notes/LDMS/LTObject_Store/ltobjst10.nsf/DDE300B846EED9C7CA257616000A3571/A91560E8BC90CB6CCA258472001094B8/$FILE/93-119aa026%20authorised.pdf)
- [x] WA https://www.legislation.wa.gov.au/legislation/statutes.nsf/law_a639.html

Misc
- [x] Check against data.gov.au export
https://data.gov.au/dataset/ds-dga-b1bc6077-dadd-4f61-9f8c-002ab2cdff10/details
- [x] Check against (or update)
https://www.australia.gov.au/about-australia/special-dates-and-events/public-holidays.html 
(see https://github.com/govau/australia-gov-au-static/issues/107)

### CODE REVIEW

**Comment by svict4** [comment]
WIP

```
ACT
01-01 and if saturday,sunday then next monday:
substitutes 01-26 if saturday,sunday then next monday:
2nd monday in March:
easter -2:
easter -1:
easter:
easter 1:
substitutes 04-25 if sunday then next monday:
monday after 04-27:
2nd monday in June:
1st monday in October:
12-25 and if saturday then next monday:
12-25 and if sunday then next tuesday:
12-26 and if saturday then next monday:
12-26 and if sunday then next tuesday:

NSW
01-01 and if saturday,sunday then next monday:
substitutes 01-26 if saturday,sunday then next monday:
easter -2:
easter -1:
easter:
easter 1:
04-25:
2nd monday in June:
1st monday in October:
12-25 and if saturday then next monday:
12-25 and if sunday then next tuesday:
12-26 and if saturday then next monday:
12-26 and if sunday then next tuesday:

NT
01-01 and if saturday,sunday then next monday:
substitutes 01-26 if saturday,sunday then next monday:
easter -2:
easter -1:
easter 1:
substitutes 12-25 if sunday then next monday:
1st monday in May:
2nd monday in June:
1st monday in August:
12-24 19:00:
12-25 and if saturday,sunday then next monday:
substitutes 12-26 if saturday then next monday:
substitutes 12-26 if sunday then next tuesday:
12-31 19:00:

QLD
01-01 and if saturday,sunday then next monday:
substitutes 01-26 if saturday,sunday then next monday:
easter -2:
easter -1:
easter:
easter 1:
substitutes 12-25 if sunday then next monday:
1st monday in May:
1st monday in October:
12-25 and if saturday then next monday:
12-25 and if sunday then next tuesday:
12-26 and if saturday then next monday:
12-26 and if sunday then next tuesday:

```

**Comment by svict4** [comment]
For your review @BrendanCNg once I get this PR ready

**Comment by svict4** [comment]
Currently awaiting a response from the [Tasmania Law Reform Institute](https://www.utas.edu.au/law-reform) as the written law regarding generating one or two public holidays depending if it lands on a weekend, is interpreted differently by one of the Government agencies, compared to my reading.

**Comment by svict4** [comment]
Advice from WorkSafe Tasmania:

> ... if New Year’s Day falls on a weekend then the following Monday is the only substitute holiday [S.4 (a) of the Act]. This is also the situation with Australia Day [S.4 (b) of the Act] and Boxing Day [S.4 (j) of the Act].

> However if Christmas Day falls on a weekend there are two statutory holidays: Christmas Day on 25th December [S.4 (i) of the Act], and either the Monday or Tuesday following [S.4 (ia) or (ib) of the Act].

**Comment by svict4** [comment]
Can't guarantee with certainty that previous years (2019) will work for all states,
but it should work for 2020 and any future year (at time of writing)

**Comment by commenthol** [comment]
Great work. Thanks a lot for your contribution. 
I've added your links to the legislation pages.

**Pull request merged**
