### PR TITLE
labor day spelling fix

### PR DESCRIPTION
**Pull request by jamesdixon**
This fixes the spelling for US english.

### CODE REVIEW

**Comment by jamesdixon** [comment]
@commenthol I just realized this also effects Australia and other English-speaking countries. Any desire to add a distinction for US english which annoyingly is different from most others?

**Comment by commenthol** [comment]
Hi @jamesdixon, I would like to solve this issue as with "de" and "de-at". 

Apart from not being able to say which is the "correct" language I would suggest the following:
```
  05-01:
    name:
      en: Labour Day
      en-us: Labor Day
```
and update the holidays countries accordingly.

**Comment by jamesdixon** [comment]
@commenthol that sounds like a solid solution 👍

**Comment by jamesdixon** [comment]
closing in favor of #11

**Pull request closed without merging**
