### PR TITLE
labor day for en-us

### PR DESCRIPTION
**Pull request by commenthol**
Proposal for PR #7

### CODE REVIEW

**Comment by commenthol** [comment]
@jamesdixon  Could you please check if this fits the purpose? Thanks

**Comment by jamesdixon** [comment]
@commenthol do all other `en` holidays need to have a `en-us` entry or will it fall back to `en` if an entry for `en-us` does not exist?

**Comment by commenthol** [comment]
Per default the 1st lang is selected. If no label can be found then the next language is chosen and a label is searched. Fallback for all counties is always `en`. 
So lets take CA. Per default now `en-us` is used with primarily using `en` names. If `fr` is selected then `en` would be the fallback. As we have a translation for 05-01 in French in this specific case, we should not run into any troubles.

**Comment by jamesdixon** [comment]
Perfect! Looks great to me

**Comment by jamesdixon** [comment]
Thank you

**Pull request merged**
