### PR TITLE
Fix typing of HolidaysConstructor

### PR DESCRIPTION
**Pull request by oscarlgz**

### CODE REVIEW

**Comment by gerryster** [comment]
I am seeing a build error:

```
Error: /home/travis/build/commenthol/date-holidays/types/index.d.ts:65:14
ERROR: 65:14  unified-signatures  This overload and the one on line 64 can be combined into one signature with an optional parameter.
```

**Comment by oscarlgz** [comment]
My bad @gerryster! Code has been updated

**Comment by gerryster** [comment]
Hey @oscarlgz: the intent here is for the type checker to enforce that the more specific state and region parameters can not be passed in by themselves? For example, after your change, it would not be possible to call the constructor and only pass in a region but omit country and state.

**Comment by oscarlgz** [comment]
Hi @gerryster,

The point is just to match the variadic nature of the constructor function. Currently if you wish to create a new Holidays instance with just the options argument, you'd have to call it like so:

```
const hd = new Holidays(undefined, undefined, undefined, {
  types: ['public']
})
```

My PR allows TypeScript users to call it with any of:

```
const hd = new Holidays()
const hd = new Holidays(country)
const hd = new Holidays(country, state)
const hd = new Holidays(country, state, language)
const hd = new Holidays(country, state, language, options)
```

The type signature arguments are currently all optional but depend on their positional arrangement, which is not what's intended. It could be argued that the `state` argument should be optional in all of the overloads, as it's not applicable to all countries. Let me know and I'll update the PR.

**Comment by gerryster** [comment]
Right, this is a nice improvement. I am newer to TypeScript so I incorrectly read the new type signatures as keyword parameters rather than positional parameters. Let me take a closer look, but I like where this is going.

**Comment by commenthol** [comment]
Thanks a lot.

**Pull request merged**
