### PR TITLE
feat(US): Easter Sunday observed in US

### PR DESCRIPTION
**Pull request by barwin**
Too late for this year, but hoping to get this in for next year.

A lot of businesses in the US close on Easter Sunday, but maybe there was a reason it was excluded. I didn't find anything in past issues or pull-requests that mentioned it, so I hope this is a reasonable addition.

Thanks in advance!
-Ben

### CODE REVIEW

**Comment by gerryster** [comment]
This makes sense to me as an observance. Thanks for contributing.

**Comment by barwin** [comment]
Awesome. Thanks for maintaining a very useful lib, @gerryster

**Comment by gerryster** [comment]
I am glad you find it useful @barwin. I want to give @commenthol a chance to comment before merging. I am merely a humble helper on this project.

**Comment by commenthol** [comment]
Thanks a lot for contributing

**Comment by barwin** [comment]
Thanks @commenthol !

**Pull request merged**
