### PR TITLE
 New Country Phillipines (Regular and Non-Working Holidays) 

### PR DESCRIPTION
**Pull request by jwh-hutchison**
Fixed holidays implemented, 'movable' (holidays susceptible to date changes are not included) to avoid issues if left unchanged in future.

### CODE REVIEW

**Comment by commenthol** [comment]
FYI -  I made some changes to the yaml file, moved name to the names.yaml file and changed the dates to month-day (MM-DD) notation. With this the testcases were generated. Maybe you like to take a look at the changes if they are correct. The test files are in test/fixtures/PH-201x.json. Please let me know if something needs to be changed. Thanks.

**Comment by jwh-hutchison** [comment]
Hi,


You're welcome, great work on maintaining the repo btw. Yeah sorry, I was in a bit of a rush and I knew I might've missed a few things worth looking back on, thanks a lot for correcting them.


Kind regards,

Jeff

________________________________

**Comment by jwh-hutchison** [comment]
Hi,


I'm just emailing to ask when changes in the github repo will take effect in the npmjs module page (in which it can be downloaded)?

Thanks

________________________________

**Comment by commenthol** [comment]
Will need to publish a new patch release on npm first. Hope I can schedule this today.

**Pull request merged**
