### PR TITLE
fix(SI): Mark Slovenian bank holidays

### PR DESCRIPTION
**Pull request by janicerar**

### CODE REVIEW

**Comment by commenthol** [comment]
Hi @janicerar,
With this PR you are proposing that Slovenia does not celebrate public or national holidays.
May I please ask you to take a look at https://github.com/commenthol/date-holidays/blob/master/docs/specification.md#types-of-holidays and check if your proposal matches the holiday types used in this project?
Furthermore I would appreciate if you could name a source for reference.

**Comment by janicerar** [comment]
Hi,

Look here https://www.gov.si/en/topics/national-holidays/

National Holidays
1 and 2 January: New Year Holiday
8 February: Prešeren Day, the Slovenian Cultural Holiday
27 April: Day of Uprising Against the Occupation
1 and 2 May: Labour Day
8 June: Primož Trubar Day*
25 June: Statehood Day
17 August: Unification of Prekmurje Slovenes with the Mother Nation*
15 September: Return of Primorska to the Motherland*
23 September: Slovenian Sports Day*
25 October: Sovereignty Day*
1 November:  Day of Remembrance for the Dead
23 November: Rudolf Maister Day*
26 December: Independence and Unity Day
* Not a work-free day.

Other work-free days
Easter Sunday, Easter Monday
Whit Sunday– Whitsuntide Holiday
15 August– Feast of the Assumption
31 October– Reformation Day
25 December– Christmas Day

**Comment by janicerar** [comment]
@commenthol  can you check this?

**Comment by commenthol** [comment]
@janicaerar 
To make it clear I think you have not considered the attribution which is used in this project as defined by its specification under **Types of holidays**.

Currently the following type with their meaning are supported

|type | meaning |
| --- | --- |
|public | public holiday |
|bank | bank holiday, banks and offices are closed |

A **public** holiday is not considered a **bank** holiday.
If the holiday is not explicitely attributed, it is considered as **public**.

Again as said I do still not believe that Slovenia does not celebrate any public holidays. 
Therefore I cannot consider accepting your PR.

**Pull request closed without merging**
