### PR TITLE
corrected HU holidays and added translations

### PR DESCRIPTION
**Pull request by tothadi**

### CODE REVIEW

**Comment by tothadi** [comment]
Could someone provide me info on what am I doing wrong?

**Comment by commenthol** [comment]
Please check CONTRIBUTING.md for the details.
TLTR
```
npm run yaml
npx mocha test/all.mocha.js --writetests --countries HU
```

**Comment by tothadi** [comment]
> Please check CONTRIBUTING.md for the details.
> TLTR
> 
> ```
> npm run yaml
> npx mocha test/all.mocha.js --writetests --countries HU
> ```

Thanks. now it worked.

**Comment by tothadi** [comment]
Could someone merge this, pls?

**Pull request merged**
