### PR TITLE
Fix several DE holidays

### PR DESCRIPTION
**Pull request by leipert**
Thanks for the great package ❤️ 

This fixes several DE holidays, I tried created atomic commits with nice commit messages for each change and I hope they are fine with you. If you have any question, feel free to ask.

### CODE REVIEW

**Comment by leipert** [comment]
I did not realize that the german dataset was used for tests beyond the fixtures :)

**Comment by commenthol** [comment]
Hi @leipert, Thanks for this great PR.

Justa a remark: What happens with DE-by-a (Stadt Augsburg) for 08-15 (Mariä Himmelfahrt). This would be a school holiday only. Correct? According to the map in https://www.statistik.bayern.de/medien/statistik/zensus/karte_mari___himmelfahrt_2014.pdf for the majority this is a public holiday. I would suggest to keep the attribution in DE-by and extend it by something like

```yaml
by:
  name: Bayern
  days:
    ...
    08-15:
      _name: 08-15
    ...
  regions:
    a:
      name: Stadt Augsburg
      days:
        08-08:
          name:
            de: Augsburger Friedensfest
            en: Augsburg Peace Festival
    ev:
      name:
        de: Überwiegend evangelische Gemeinden
        en: Predominantly protestant communities
      days:
        08-15:
          _name: 08-15
          type: school
```

What do you think?

**Comment by commenthol** [comment]
For Bautzen I would prefer to see the region name together with a note
```yaml
sn:
  name: Sachsen
  days:
    easter 60:
      _name: easter 60
      type: observance
    10-31:
      _name: Reformation Day
     wednesday before 11-23:
       _name: Buß- und Bettag
  regions:
    bz:
      name: Landkreis Bautzen
      days:
        easter 60:
          _name: easter 60
          type: public
          note: Bautzen (nur in den Ortsteilen Bolbritz und Salzenforst), Crostwitz, Göda (nur im Ortsteil Prischwitz), Großdubrau (nur im Ortsteil Sdier), Hoyerswerda (nur im Ortsteil Dörgenhausen), Königswartha (nicht im Ortsteil Wartha), Nebelschütz, Neschwitz (nur in den Ortsteilen Neschwitz und Saritsch), Panschwitz-Kuckau, Puschwitz, Räckelwitz, Radibor, Ralbitz-Rosenthal und Wittichenau.
```

**Comment by commenthol** [comment]
For "Eichsfeld", "Unstrut-Hainich-Kreis" and "Wartburgkreis" I would prefer the same
```yaml
th:
  name: Thüringen
  days:
    10-31:
      _name: Reformation Day
    '12-31 14:00 if sunday then 00:00':
      _name: 12-31
  regions:
    eic:
      name: Landkreis Eichfeld
      days:
        easter 60:
          _name: easter 60
          type: public
    uh:
      name: Unstrut-Hainich-Kreis
      days:
        easter 60:
          _name: easter 60
          type: public
          note: In Anrode (nur in den Ortsteilen Bickenriede und Zella), Dünwald (nur in den Ortsteilen Beberstedt und Hüpstedt), Rodeberg (nur im Ortsteil Struth), Südeichsfeld

    wak:
      name: Wartburgkreis
      days:
        easter 60:
          _name: easter 60
          type: public
          note: In Brunnhartshausen (nur in den Ortsteilen Föhlritz und Steinberg), Buttlar, Geisa, Schleid, Zella/Rhön
```

**Comment by commenthol** [comment]
Will "Fronleichnam" then be observed in whole TH and SN?

**Comment by commenthol** [comment]
Thanks for clarifying things. I have now included the changes as stated above in the PR. Would be nice if you could check them. Thx.

**Comment by leipert** [comment]
Thanks 👍

**Comment by leipert** [comment]
Your changes LGTM, I wanted to implement them today, but you were faster :)

**Pull request merged**
