### PR TITLE
Updated bank holidays and non-working days for Switzerland

### PR DESCRIPTION
**Pull request by iiome**
Hi,

NB. using MM-DD format for dates in this message.

I've checked and updated bank holidays for all the cantons in Switzerland.

Some canton have non-working days meaning that administrations and some company are closed but those days are not qualified as bank (or public) holidays.

For the Canton of Neuchatel I've implemented the substitute rules for 01-01 and 12-25 (if it fall on a sunday then the next day is a bank holiday).

For LU (03-19, Saint-Joseph) the bank holidays is supposed to be half a day and this will be further improved when I will get to the details.

Some cities in Switzerland also have special days (Le Landeron, Cerneux-Péquignot). Those will be covered in futur updates.

### CODE REVIEW

**Comment by commenthol** [comment]
Hi Guillame,

Thanks a lot for the PR. Swiss holidays are a really hard puzzle to solve...

Some comments from my side:

- "Saint-Berthold" is named in french. Shouldn't this be "Saint Berchtold"?

According to https://www.bj.admin.ch/dam/data/bj/publiservice/service/zivilprozessrecht/kant-feiertage.pdf

4. Kanton Uri & 15. Kanton Appenzell A. Rh. & 16. Kanton Appenzell I. Rh. 
  - 12-26 is only valid if not on Mo or Fr (this needs a new rule - will open an issue)

7. Kanton Nidwalden
  - Berchtoldstag seams to be missing

8. Kanton Glarus
  - "thursday after 04-01" Fahrtsfest - not part of list - Can you please name a source?
  - "monday after 3 sunday after 09-01" - not part of list - Can you please name a source?
    - `de: Federal Fast Montag` Shouldn't it be "Bettag"?
    - in `en: Day of Prayer and Repentance`?
17. Kanton St. Gallen
  - 08-15 does not seam to be an holiday at all. Right?

19. Kanton Aargau
  - 11-01 Allerheiligen seams to be an official holiday

21. Cantone del Ticino
  - 12-26 seams to be a holiday. Right?

22. Canton de Vaud
  - "monday after 3 sunday after 09-01"
    - `de: Federal Fast Montag` Shouldn't it be "Bettag"?
    - in `en: Day of Prayer and Repentance`?

23. Canton du Valais / Kanton Wallis
  - Berchtoldstag seams to be missing
  - 12-26 should be optional?

24. Canton de Neuchâtel / Kanton Neuenburg
  - rule does not make sense as `_name: 02-01` is not defined.
    ```
    01-01 if sunday then next monday:
      _name: 02-01
    ``` 
    should it be?
    ```
    01-01 if sunday then next monday:
      _name: 01-01
      substitute: true
    ``` 

25. Canton de Genève
  - "monday after 3 sunday after 09-01"
    - `de: Genf schnell` Shouldn't it be "Genfer Bettag"?
    - in `en: Day of Prayer and Repentance`?

**Comment by iiome** [comment]
> Some comments from my side:
> 
> * "Saint-Berthold" is named in french. Shouldn't this be "Saint Berchtold"?

yes it should. 
fr: Saint-Berthold
de: Berchtoldstag https://en.wikipedia.org/wiki/Berchtoldstag
en: wikipedia features Berchtoldstag sounds like Saint Berchtold in English https://en.wikipedia.org/wiki/Berchtoldstag

> According to https://www.bj.admin.ch/dam/data/bj/publiservice/service/zivilprozessrecht/kant-feiertage.pdf

I've mainly used the Wikipedia page french version to check all the local bank holidays. I believe your source is much better.
 
> 1. Kanton Uri & 15. Kanton Appenzell A. Rh. & 16. Kanton Appenzell I. Rh.
> 
> * 12-26 is only valid if not on Mo or Fr (this needs a new rule - will open an issue)

I've seen it on the PDF. sounds good.
 
> 1. Kanton Nidwalden
> 
> * Berchtoldstag seams to be missing

and this one should be of type optional

> 1. Kanton Glarus
> 
> * "thursday after 04-01" Fahrtsfest - not part of list - Can you please name a source?

I've found them originally on Wikipedia / French https://fr.wikipedia.org/wiki/Jours_f%C3%A9ri%C3%A9s_en_Suisse

and it is part of the list (4th entry on a.)

> * "monday after 3 sunday after 09-01" - not part of list - Can you please name a source?

I believe I was wrong for this one.

>   * `de: Federal Fast Montag` Shouldn't it be "Bettag"?
>   * in `en: Day of Prayer and Repentance`?

I would rely on on Wikipeida for those
* https://de.wikipedia.org/wiki/Eidgen%C3%B6ssischer_Dank-,_Buss-_und_Bettag
* https://en.wikipedia.org/wiki/Federal_Day_of_Thanksgiving,_Repentance_and_Prayer
 
> 1. Kanton St. Gallen
> 
> * 08-15 does not seam to be an holiday at all. Right?

you are right

> 
> 1. Kanton Aargau
> 
> * 11-01 Allerheiligen seams to be an official holiday

this one missing on the french Wikipedia https://fr.wikipedia.org/wiki/Jours_f%C3%A9ri%C3%A9s_en_Suisse

and neither can I find it in the Kanton page about it
https://www.ag.ch/de/dvi/strassenverkehr/feiertage_3/departement_detailseite_367.jsp

I think that we should add it

> 1. Cantone del Ticino
> 
> * 12-26 seams to be a holiday. Right?

right!

> 1. Canton de Vaud
> 
> * "monday after 3 sunday after 09-01"
>   
>   * `de: Federal Fast Montag` Shouldn't it be "Bettag"?
>   * in `en: Day of Prayer and Repentance`?

Well Bettag (or in french le "Jeûne Fédéral") is going to be on Sunday. In french people would say "Lundi du Jeûne"

> 1. Canton du Valais / Kanton Wallis
> 
> * Berchtoldstag seams to be missing
> * 12-26 should be optional?
 
both are missing on https://fr.wikipedia.org/wiki/Jours_f%C3%A9ri%C3%A9s_en_Suisse

both are missing from the Canton website https://www.vs.ch/fr/web/srh/plan-de-travail

but if you open the PDF for 2018 https://www.vs.ch/documents/79255/1990573/Plan%20de%20travail%202018.pdf/892325aa-50ca-4dd4-9f22-4afa488158c2?t=.now?long you can find the 26th as being non-working / grey background. (and their are many more days).

> 1. Canton de Neuchâtel / Kanton Neuenburg
> 
> * rule does not make sense as `_name: 02-01` is not defined.
>   ```
>   01-01 if sunday then next monday:
>     _name: 02-01
>   ```
>   should it be?
>   ```
>   01-01 if sunday then next monday:
>     _name: 01-01
>     substitute: true
>   ```

yes! but I was not able to make it work.

> 1. Canton de Genève
> 
> * "monday after 3 sunday after 09-01"
>   
>   * `de: Genf schnell` Shouldn't it be "Genfer Bettag"?
>   * in `en: Day of Prayer and Repentance`?

yes!

Extra last question. I am frustrated because I get all the Canton name in German whereas I feel it would be useful to get them in German, French, Italian and English. Is this possible ? I didn't figure it out yet.

Anyways thank you so much for considering my push request and taking the time to dig all those specificities.

**Comment by commenthol** [comment]
With regards to the different region/ state name translations I have to check in the parser.
In case that this is not yet implemented I can try to prepare a PR. 
With respect to the new rule for Stefanstag 12-26 it is ready and I could update all necessary packages if you like to. See https://github.com/commenthol/date-holidays-parser/pull/4

**Comment by commenthol** [comment]
Just checked. Yes different translations for states and regions is implemented.

As example for `CH.ZH` change

    states:
      ZH:
        name: Kanton Zürich


to

    states:
      ZH:
        names: 
          de: Kanton Zürich
          fr: Canton de Zurich
          en: Canton of Zürich
          it: Cantone di Zurigo

**Comment by iiome** [comment]
thank you, for the names. Can I be of any help regarding the different holidays?

**Comment by commenthol** [comment]
@iiome: Sorry for my late response. Yes sure if you like to update the holidays according to the different sources I would be very thankful. Do you like to update this in this PR?

**Comment by commenthol** [comment]
Hi @iiome,
Thanks for your work.
I had to manually merge your commits due to merge conflicts. All your commits are now on master. See https://github.com/commenthol/date-holidays/commits/master.  Github does not seam to have recognized those changes. 
I am closing this pull request as all commits are "merged". 
Could you please be so kind and check if the holidays I have added/ modified. There are so many confusing sources...

**Comment by iiome** [comment]
@commenthol sorry for the late reply, thank you very much

**Comment by commenthol** [comment]
You are welcome. Thanks as well.

**Pull request closed without merging**
